name: fireblend
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  test: 1.24.3 
  analyzer: 5.13.0
  # https://github.com/dart-lang/sdk/issues/39702
